---
name: Base
description: Base layer with standard QWERTY layout and layer switching
mapping:
  tab: Tab
  Q: Q
  W: W
  E: E
  R: R
  T: T
  lctrl: LCtrl
  A: A
  S: S
  D: D
  F: F
  G: G
  lshift: LShift
  Z: Z
  X: X
  C: C
  V: V
  B: B
  caps: CapsLock
  fn: MO(3)
  option: LAlt
  command: LGUI_T(KC_LANG2)
  space: LT1(Space)
  esc: LT2(Escape)
  Y: Y
  U: U
  I: I
  O: O
  P: P
  backspace: Backspace
  H: H
  J: J
  K: K
  L: L
  colon: ;
  backslash: \
  N: N
  M: M
  comma: ","
  dot: .
  slash: Slash
  rshift: RSFT_T(Up)
  enter: LT2(Enter)
  raise: MO(1)
  lang: LT3(KC_LANG1)
  left: Left
  down: Down
  right: Right
  l_rotary_push: Mute
  l_rotary_ccw: VolumeDown
  l_rotary_cw: VolumeUp
  r_rotary_push: OSL(9)
  r_rotary_ccw: MouseWheelRight
  r_rotary_cw: MouseWheelLeft
