---
name: Layer 1
description: Layer 1
overrides:
  tab: Escape
  Q: '1'
  W: '2'
  E: '3'
  R: '4'
  T: '5'
  lctrl: NoKey
  A: NoKey
  S: NoKey
  D: NoKey
  F: ";"
  G: "-"
  lshift: NoKey
  Z: NoKey
  X: NoKey
  C: NoKey
  V: NoKey
  B: NoKey
  caps: NoKey
  fn: NoKey
  option: NoKey
  command: NoKey
  space: NoKey
  esc: NoKey
  "Y": '6'
  U: '7'
  I: '8'
  O: '9'
  P: '0'
  backspace: Delete
  H: "="
  J: "'"
  K: NoKey
  L: NoKey
  colon: NoKey
  backslash: NoKey
  "N": NoKey
  M: NoKey
  comma: NoKey
  dot: NoKey
  up: NoKey
  rshift: NoKey
  enter: NoKey
  raise: NoKey
  lang: NoKey
  left: NoKey
  down: NoKey
  right: NoKey
