---
name: Layer 6
description: ''
index: 6
mapping:
  left_hand:
    row0:
      tab: NoKey
      Q: NoKey
      W: NoKey
      E: NoKey
      R: NoKey
      T: NoKey
    row1:
      caps: NoKey
      A: NoKey
      S: NoKey
      D: NoKey
      F: NoKey
      G: NoKey
    row2:
      lshift: NoKey
      Z: NoKey
      X: NoKey
      C: NoKey
      V: NoKey
      B: NoKey
    row3:
      lctrl: NoKey
      command: NoKey
      option: NoKey
    thumb_keys:
      left: NoKey
      middle: NoKey
      right: NoKey
  right_hand:
    row0:
      "Y": NoKey
      U: NoKey
      I: NoKey
      O: NoKey
      P: NoKey
      backspace: NoKey
    row1:
      H: NoKey
      J: NoKey
      K: NoKey
      L: NoKey
      colon: NoKey
      enter: NoKey
    row2:
      "N": NoKey
      M: NoKey
      comma: NoKey
      dot: NoKey
      up: NoKey
      rshift: NoKey
    row3:
      left: NoKey
      down: NoKey
      right: NoKey
    thumb_keys:
      left: NoKey
      middle: NoKey
      right: NoKey
  encoders:
    left:
      push: Mute
      ccw: VolumeDown
      cw: VolumeUp
    right:
      push: MouseButton3
      ccw: MouseWheelUp
      cw: MouseWheelDown