---
name: Layer 9
description: Layer 9
overrides:
  tab: NoKey
  Q: NoKey
  W: NoKey
  E: NoKey
  R: NoKey
  T: NoKey
  lctrl: NoKey
  A: NoKey
  S: NoKey
  D: NoKey
  F: NoKey
  G: NoKey
  lshift: NoKey
  Z: NoKey
  X: NoKey
  C: NoKey
  V: NoKey
  B: NoKey
  caps: NoKey
  fn: NoKey
  option: NoKey
  command: NoKey
  space: NoKey
  esc: NoKey
  "Y": NoKey
  U: NoKey
  I: NoKey
  O: NoKey
  P: NoKey
  backspace: NoKey
  H: NoKey
  J: NoKey
  K: NoKey
  L: NoKey
  colon: NoKey
  backslash: NoKey
  "N": NoKey
  M: NoKey
  comma: NoKey
  dot: NoKey
  up: NoKey
  rshift: NoKey
  enter: NoKey
  raise: NoKey
  lang: NoKey
  left: NoKey
  down: NoKey
  right: NoKey
